### ISSUE TITLE
College status page checklist. (Now college status pages.)

### ISSUE THREAD

**Issue by santaclauslives** [santaclauslives/web-app__swimming-competition#1]
Steps 
- [ ] I don't often talk to myself in the second person, but I am so bad at this particular entry that I will here. Commit every time you make a material change to code. A material change is almost any change to the operation or documentation of a function of the program. It produces or eliminates an error message, TomDoc, changes the appearance of a page (do last) or any other event in the life of the code. Now this project:
- [x] Getting or modifying info? GET
- [x] Part of page or whole page? WHOLE PAGE
- [x] How does this feature get triggered. From links on the home page. Similar to the race status pages, there would be a link for each school's information.
- [x] What's the response? The view page is college_status.erb.
- [x] Controller action: I have set up a controller action MyApp.get "/college_view" do with the erb "college status". In that controller action I also set up @colleges = College.all so I could use the "@colleges" on the view page. 
- [x] NEW WORK - I may need to add a variable to the controller action, like MyApp.get "/college_view/:id" where the id is a college id, if I am going to switch to individual college pages. That is what I did for the race pages. It makes for a lot of links on the home page, but I'm getting ahead of myself here. 
- [x] Dream erb page = The dream is a page with the name of the school, the conference name, the college's contact person, contact email and contact phone. I guess it would be good to add their swimmers, but I'm not going to deal with that now.
  Page has evolved. My original thought was to have the names of all schools - all of their respective conferences - all of their contact data. Kind of a display of the entire college table, with the conference name substituted for the conference id. The one-college per page format seems more doable in the time frame.
- [x] I need to re-think and re-do my method for getting conference names. It is on college.rb in the Models pages. 
- [x] Display this page with just the name of "college 1" on it. That would be a step forward. 
- [x] Display this page with that college's other data from the college table.
- [x] Display this page with that college's data and the conference name from the conference table. 
- [x] Make a link on the home page to just this stage.
- [x] If the link works, replicate the link and change the id variable to 2, in hopes of getting school 2 data. There are 4 colleges in the meet. 
- [x] If the link works, replicate the link and change the id variable to 3, in hopes of getting school 3 data. There are 4 colleges in the meet. 
- [x] If the link works, replicate the link and change the id variable to 4, in hopes of getting school 4 data. There are 4 colleges in the meet.

**Comment by santaclauslives** [comment]
Where did my check boxes go?
